# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contact1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900,635)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 0, 511, 101))
        self.label.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 150, 351, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 4, 3, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 3, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 5, 1, 1, 3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 6, 1, 1, 3)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(460, 150, 321, 381))
        self.listWidget.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.listWidget.setObjectName("listWidget")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(460, 540, 113, 22))
        self.lineEdit_5.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(370, 590, 471, 16))
        self.label_6.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 540, 93, 28))
        self.pushButton_2.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(680, 540, 93, 28))
        self.pushButton_4.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.add_contact)
        self.pushButton_2.clicked.connect(self.search_contact)
        self.pushButton_3.clicked.connect(self.update_contact)
        self.pushButton_4.clicked.connect(self.delete_contact)


    def add_contact(self):
        # Get the contact information from the input fields
        name = self.lineEdit.text()
        phone = self.lineEdit_2.text()
        email = self.lineEdit_3.text()
        address = self.lineEdit_4.text()

        # Check if name and phone are not empty
        if name and phone:
            contact_info = f"{name},{phone},{email},{address}"
            self.listWidget.addItem(contact_info)
            self.clear_fields()
        else:
            QtWidgets.QMessageBox.critical(None, "Error", "Name and Phone are required fields.")

    def clear_fields(self):
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()

   
    def update_contact(self):
        selected_item = self.listWidget.currentItem()
        if selected_item:
            name = self.lineEdit.text()
            phone = self.lineEdit_2.text()
            email = self.lineEdit_3.text()
            address = self.lineEdit_4.text()


            if name and phone and email and address:
                updated_contact_info = f"{name}, {phone}, {email}, {address}"
                selected_item.setText(updated_contact_info)
                self.clear_fields()

            else:
                QtWidgets.QMessageBox.critical(None, "Error", "Name and Phone are required fields.")
        else:
            QtWidgets.QMessageBox.warning(None, "No Contact Selected", "Please select a contact to update.")

        



    def delete_contact(self):
        selected_item = self.listWidget.currentItem()
    
        if selected_item:
            confirmation = QtWidgets.QMessageBox.question(None,"Delete Contact","Are you sure you want to delete this contact?",
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
        
            if confirmation == QtWidgets.QMessageBox.Yes:
                self.listWidget.takeItem(self.listWidget.row(selected_item))
                self.clear_fields()
        else:
            QtWidgets.QMessageBox.warning(None, "No Contact Selected", "Please select a contact to delete.")
    def search_contact(self):
        search_name = self.lineEdit_5.text()
        found = False
    
    # Iterate through the items in the listWidget to find the contact
        for index in range(self.listWidget.count()):
            contact = self.listWidget.item(index).text()
            if search_name in contact:
                found = True
                break

        if found:
            self.label_6.setText(contact)
        else:
            self.label_6.setText("Contact not found")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Contact Manager"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Enter Your Address"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Enter Your Email Id"))
        self.label_3.setText(_translate("MainWindow", "Phone:"))
        self.label_5.setText(_translate("MainWindow", "Address:"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter Your Name"))
        self.pushButton.setText(_translate("MainWindow", "Add Contact"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Enter Your Number"))
        self.label_2.setText(_translate("MainWindow", "Name:"))
        self.label_4.setText(_translate("MainWindow", "Email:"))
        self.pushButton_3.setText(_translate("MainWindow", "Update"))
        self.pushButton_2.setText(_translate("MainWindow", "search"))
        self.pushButton_4.setText(_translate("MainWindow", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
